// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMGQtLv3Z41Si1VgqUlEBZI9JaT3jp5no',
    appId: '1:191347874730:web:eda36c2434def3fc0669d3',
    messagingSenderId: '191347874730',
    projectId: 'solarmonitoringsystem-53551',
    authDomain: 'solarmonitoringsystem-53551.firebaseapp.com',
    storageBucket: 'solarmonitoringsystem-53551.firebasestorage.app',
    measurementId: 'G-PHTXSP2K2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDih0Dw5SxBu11YAoUA5dWQxzkgB5jhwRg',
    appId: '1:191347874730:android:9756b705088388d60669d3',
    messagingSenderId: '191347874730',
    projectId: 'solarmonitoringsystem-53551',
    storageBucket: 'solarmonitoringsystem-53551.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYobJkPazLRmeTPh-0DirDtYdJBJ1GXO4',
    appId: '1:191347874730:ios:f0dffbfca11b20770669d3',
    messagingSenderId: '191347874730',
    projectId: 'solarmonitoringsystem-53551',
    storageBucket: 'solarmonitoringsystem-53551.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYobJkPazLRmeTPh-0DirDtYdJBJ1GXO4',
    appId: '1:191347874730:ios:f0dffbfca11b20770669d3',
    messagingSenderId: '191347874730',
    projectId: 'solarmonitoringsystem-53551',
    storageBucket: 'solarmonitoringsystem-53551.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMGQtLv3Z41Si1VgqUlEBZI9JaT3jp5no',
    appId: '1:191347874730:web:3a265f28499e955b0669d3',
    messagingSenderId: '191347874730',
    projectId: 'solarmonitoringsystem-53551',
    authDomain: 'solarmonitoringsystem-53551.firebaseapp.com',
    storageBucket: 'solarmonitoringsystem-53551.firebasestorage.app',
    measurementId: 'G-F23QXMCH3N',
  );
}
